// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTMKzvRTB6wlelUuIISsXP2hE5E1SCxtI',
    appId: '1:862009695575:web:bfdec88889a590f5a63212',
    messagingSenderId: '862009695575',
    projectId: 'firestore-ba193',
    authDomain: 'firestore-ba193.firebaseapp.com',
    storageBucket: 'firestore-ba193.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgG1xErI-QGQPbqE80xGqG3wI9JPxdYEg',
    appId: '1:862009695575:android:856742839368d7bfa63212',
    messagingSenderId: '862009695575',
    projectId: 'firestore-ba193',
    storageBucket: 'firestore-ba193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2ZFNy2eu9e4x-QmXQ8mqyI75UloSEOrs',
    appId: '1:862009695575:ios:d3bcfc2e3addeef7a63212',
    messagingSenderId: '862009695575',
    projectId: 'firestore-ba193',
    storageBucket: 'firestore-ba193.appspot.com',
    iosBundleId: 'com.example.firestoreAppTi43',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2ZFNy2eu9e4x-QmXQ8mqyI75UloSEOrs',
    appId: '1:862009695575:ios:d3bcfc2e3addeef7a63212',
    messagingSenderId: '862009695575',
    projectId: 'firestore-ba193',
    storageBucket: 'firestore-ba193.appspot.com',
    iosBundleId: 'com.example.firestoreAppTi43',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTMKzvRTB6wlelUuIISsXP2hE5E1SCxtI',
    appId: '1:862009695575:web:17c7e9528e326e7ea63212',
    messagingSenderId: '862009695575',
    projectId: 'firestore-ba193',
    authDomain: 'firestore-ba193.firebaseapp.com',
    storageBucket: 'firestore-ba193.appspot.com',
  );

}